import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#eaddff",
        "surface-container-low": "#f2f3ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#713700",
        "surface-dim": "#d2d9f4",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#a15100",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "secondary-container": "#316bf3",
        "inverse-surface": "#283044",
        "surface-tint": "#732ee4",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed": "#301400",
        "outline-variant": "#ccc3d8",
        tertiary: "#7d3d00",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        outline: "#7b7487",
        "primary-fixed-dim": "#d2bbff",
        primary: "#630ed4",
        "on-secondary": "#ffffff",
        surface: "#faf8ff",
        "tertiary-fixed-dim": "#ffb784",
        "tertiary-fixed": "#ffdcc6",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-container": "#ffe0cd",
        "on-background": "#131b2e",
        "on-primary-container": "#ede0ff",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        secondary: "#0051d5",
        "inverse-on-surface": "#eef0ff",
        "primary-container": "#7c3aed",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed": "#25005a",
        "inverse-primary": "#d2bbff",
        background: "#faf8ff",
        "on-surface-variant": "#4a4455",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#dbe1ff",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "max-width": "1280px",
      },
      maxWidth: {
        "max-width": "1280px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
